### ISSUE TITLE
ImportError: module 'hsmwiz.__main__' has no attribute 'main'

### ISSUE THREAD

**Issue by eighthave** [johndoe31415/nitrotool#5]
When running `hsmwiz` from an installed version, as opposed to running `./hsmwiz.py` out of the git repo, it cannot start:

```console
 ~ $ hsmwiz checkengine
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/usr/lib/x86_64-linux-gnu/engines-1.1/libpkcs11.so
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
[Success]: MODULE_PATH:/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
Loaded: (pkcs11) pkcs11 engine
     [ available ]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2419, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'hsmwiz.__main__' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/hsmwiz", line 33, in <module>
    sys.exit(load_entry_point('hsmwiz==0.0.1', 'console_scripts', 'hsmwiz')())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2421, in resolve
    raise ImportError(str(exc))
ImportError: module 'hsmwiz.__main__' has no attribute 'main'
 ~ $ 
```

You might consider using the standard Python method of `entry_points` and `console_scripts` rather than the custom `MultiCommand` class:
https://www.locallyoptimal.com/blog/2014/03/14/executable-python-scripts-via-entry-points/

https://github.com/androguard/androguard is using this, for example.

**Comment by johndoe31415** [comment]
Huh, this is fairly weird on multiple levels. Firstly, in your setup, it's doing it's job, only afterwards it fails. I.e., it seems to import the pacakge __main__ and executes the code just fine, then fails to import main (which does not exist, that is correct). The issue I have is to understand why in my setup this does *not* fail. My `~/.local/bin/hsmwiz` looks like this (re/sys imports skipped):

```
from hsmwiz.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

And even though the __main__ package clearly exports no main, it works:

```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hsmwiz.__main__ import main
Error: No command supplied.
[...]
```

I'll switch to exporting a main() function and referencing this, since it's clearly a bug.

Regarding the export, the purpose of MultiCommand is to allow for OpenSSL-style commands and also accept abbreviations and aliases. I do like that so I don't think that I would want to clutter the filesystem with many executables.

I'll test this out now and hopefully have this fixed in 5 minutes.

**Comment by eighthave** [comment]
uploaded to Debian!
